version: '3'

services:
  cuentasclaras:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    restart: unless-stopped
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true