version: '3'

services:
  cuentasclaras:
    image: matiaslionel/cuentasclaras:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 0
        CACHEBUST: ${CACHEBUST:-$(date +%s)}  # Esto fuerza la reconstrucción
    ports:
      - "4000:80"
    restart: unless-stopped
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true